# Data Analysis with Python (IBM)
## Módulo 1

## El problema

**"Why Data Analysis"**



1.   Nos ayuda a contestar preguntas acerca de los datos
2.   JUega un importante rol para 


*   Descubrir información útil
*   Predecir información sobre los datos

## Python Packages for Data Science

La librería de **Pandas** de Python especializada en el manejo y análisis de estructuras de datos.

La librería **NumPy** de Python esta especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos. Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

La librería **SciPy** contiene módulos para optimización, álgebra lineal, integración, interpolación, funciones especiales, FFT, procesamiento de señales e imagen, resolución de EDOs y otras tareas relacionadas con la ciencia e ingeniería.

## Python Packages for Visualization

La librería **Matplotlib** permite crear y personalizar los tipos de gráficos más comunes, como barras, Histogramas, gráficos de líneas .. etc.

La librería **Seaborn** permite generar gráficos de alto nivel para creación de gráficas atractivas como mapas de calor, está basada en la librería de Matplotlib.

## Python Packages for Algorithmic

La librería **Scikit - learn**  es un conjunto de rutinas escritas en Python para hacer análisis predictivo, que incluyen clasificadores, algoritmos de clusterización, etc. Está basada en NumPy, SciPy y matplotlib, de forma que es fácil reaprovechar el código que use estas librerías.

La librería de **Statsmodels** proporciona clases y funciones para la estimación de muchos modelos estadísticos diferentes, así como para realizar pruebas estadísticas y exploración de datos estadísticos.

## Utilizando la librería de Pandas ...

Se pueden importar diferentes tipos de archivos como .csv, .json, .xlsx....

Para importar una base de datos se debe de poner la ruta de acceso ya sea un ruta dentro de la misma computadora o un link de internet

In [1]:
#Importando la librería pandas
import pandas as pd

In [3]:
url ='https://raw.githubusercontent.com/tec03/Datasets/main/datasets/Cereals.csv'
df = pd.read_csv(url, header = None)

In [4]:
#Si queremos ver los primeros 10 registros de la BD
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
1,100%_Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
2,100%_Natural_Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
4,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912
5,Almond_Delight,R,C,110,2,2,200,1,14,8,NaN,25,3,1,0.75,34.384843
6,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1,0.75,29.509541
7,Apple_Jacks,K,C,110,2,0,125,1,11,14,30,25,2,1,1,33.174094
8,Basic_4,G,C,130,3,2,210,2,18,8,100,25,3,1.33,0.75,37.038562
9,Bran_Chex,R,C,90,2,1,200,4,15,6,125,25,1,1,0.67,49.120253

In [5]:
#Si queremos ver los últimos 10 registros de la BD
df.tail(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
68,Special_K,K,C,110,6,0,230,1,16,3,55,25,1,1,1,53.131324
69,Strawberry_Fruit_Wheats,N,C,90,2,0,15,3,15,5,90,25,2,1,1,59.363993
70,Total_Corn_Flakes,G,C,110,2,1,200,0,21,3,35,100,3,1,1,38.839746
71,Total_Raisin_Bran,G,C,140,3,1,190,4,15,14,230,100,3,1.5,1,28.592785
72,Total_Whole_Grain,G,C,100,3,1,200,3,16,3,110,100,3,1,1,46.658844
73,Triples,G,C,110,2,1,250,0,21,3,60,25,3,1,0.75,39.106174
74,Trix,G,C,110,1,1,140,0,13,12,25,25,2,1,1,27.753301
75,Wheat_Chex,R,C,100,3,1,230,3,17,3,115,25,1,1,0.67,49.787445
76,Wheaties,G,C,100,3,1,200,3,17,3,110,25,1,1,1,51.592193
77,Wheaties_Honey_Gold,G,C,110,2,1,200,1,16,8,60,25,1,1,0.75,36.187559

Para guardar un archivo, se utiliza el siguiente código 

path = "C:\Windows\ .... \nombre.csv"
df.to_csv(path)

In [7]:
#Para saber que tipo de variables contiene la BD .....
df.dtypes

0     object
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
dtype: object

In [9]:
#Para sacar estadísticas (medidas de tendencia)...
df.describe(include ='all')

          0   1   2    3   4   5   6   7   8   9   10  11  12  13  14      15
count     78  78  78   78  78  78  78  78  77  77  76  78  78  78  78      78
unique    78   8   3   12   7   6  28  14  22  17  36   4   4   8  13      78
top     name   K   C  110   3   1   0   0  15   3  35  25   3   1   1  rating
freq       1  23  74   29  28  30   9  19   8  13   5  63  36  64  30       1